spring:
  application:
    name: User Authentication and Authorization
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?useSSL=false&serverTimezone=Asia/Manila
    username: root
    password: P4ssw0rd!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: 385f6b142deff2863b9deedcdac00a37
    expiration-ms: 3600000